#!/usr/bin/env python3
# =============================================================================
#  make_package.py — assemble a self-contained flasher folder from the ESP-IDF
#  build output, in the SAME style as the package you already flash with:
#  bootloader.bin / partition-table.bin / motor.bin + flash_args + package.env
#  + a standalone flash.ps1 that auto-downloads esptool (no ESP-IDF needed).
#
#  Run from the project root AFTER `idf.py build`. Reads build/flasher_args.json
#  so the offsets/flash settings always match what the build actually produced.
# =============================================================================
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")
OUT = os.path.join(ROOT, "dist", "motor-c3-flasher")


def main():
    fa_path = os.path.join(BUILD, "flasher_args.json")
    if not os.path.isfile(fa_path):
        sys.exit("flasher_args.json not found — run `idf.py build` first.")

    with open(fa_path) as f:
        fa = json.load(f)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)

    # flasher_args.json maps offset -> built image path. Copy each image and
    # record (offset, filename) for the flash_args file.
    entries = []
    for offset, rel in fa["flash_files"].items():
        src = os.path.join(BUILD, rel)
        name = os.path.basename(rel)
        shutil.copy(src, os.path.join(OUT, name))
        entries.append((int(offset, 16), name))
    entries.sort()

    # flash_args: first line = write_flash options, then offset/file pairs.
    wf = fa.get("write_flash_args", ["--flash_mode", "dio",
                                     "--flash_size", "4MB",
                                     "--flash_freq", "80m"])
    with open(os.path.join(OUT, "flash_args"), "w", newline="\n") as f:
        f.write(" ".join(wf) + "\n")
        for off, name in entries:
            f.write(f"0x{off:x} {name}\n")

    # package.env: metadata the flash.ps1 reads (chip, labels, reset modes).
    extra = fa.get("extra_esptool_args", {})
    before = extra.get("before", "default_reset")
    after = extra.get("after", "hard_reset")
    with open(os.path.join(OUT, "package.env"), "w", newline="\n") as f:
        f.write("# Generated by scripts/make_package.py - do not edit.\n")
        f.write('UNIT="motor"\n')
        f.write('UNIT_LABEL="motor (wheel-side) C3 PPM unit"\n')
        f.write('CHIP="esp32c3"\n')
        f.write('VERSION="esp32c3-ppm"\n')
        f.write('COMMIT="ci"\n')
        f.write(f'BEFORE="{before}"\n')
        f.write(f'AFTER="{after}"\n')

    # The standalone flasher + its README travel with the package.
    shutil.copy(os.path.join(ROOT, "package", "flash.ps1"),
                os.path.join(OUT, "flash.ps1"))
    shutil.copy(os.path.join(ROOT, "package", "PACKAGE_README.md"),
                os.path.join(OUT, "README.md"))

    print("Assembled flasher package in", OUT)
    for n in sorted(os.listdir(OUT)):
        print("  ", n)


if __name__ == "__main__":
    main()
